'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const {JSDOM} = require('jsdom');
const dom = new JSDOM('<header class="abmm-header"><div class="abmm-nav__drawer"><div class="abmm-nav__drawer-head"></div><a href="/products" target="_blank" rel="noopener">Products</a><a href="javascript:alert(1)">Unsafe</a><a class="is-disabled" href="/disabled">Disabled</a></div></header>',{url:'https://example.test/',runScripts:'outside-only'});
const w = dom.window;
w.abmmRuntime = {adminPreview:true,searchStrings:{label:'Find a destination',oneResult:'%d match',manyResults:'%d matches'}};
w.eval(fs.readFileSync('assets/js/frontend.js','utf8'));
const header = w.document.querySelector('header');
w.ABMMMenuSearch.init(header);
assert.equal(header.querySelector('.abmm-menu-search'),null,'Existing menus must not acquire search by default.');
header.classList.add('abmm-mobile-enhanced');
w.ABMMMenuSearch.init(header);
const input = header.querySelector('input');
assert.ok(input);
assert.match(header.querySelector('label').textContent,/Find a destination/);
input.value='products'; input.dispatchEvent(new w.Event('input'));
const result = header.querySelector('.abmm-menu-search__results a');
assert.equal(result.getAttribute('href'),'/products');
assert.equal(result.getAttribute('target'),'_blank');
assert.equal(result.getAttribute('rel'),'noopener');
assert.equal(header.querySelector('[role="status"]').textContent,'1 match');
input.value='unsafe'; input.dispatchEvent(new w.Event('input'));
assert.equal(header.querySelectorAll('.abmm-menu-search__results a').length,0);
header.classList.remove('abmm-mobile-enhanced');
w.ABMMMenuSearch.init(header);
assert.equal(header.querySelector('.abmm-menu-search'),null,'Turning enhancements off must remove search markup.');
assert.equal(header.classList.contains('abmm-is-searching'),false);
assert.equal(w.document.__ashbiMegaMenuExternalDrawerObserverActive,undefined,'Preview loading must not initialize global page observers.');
dom.window.close();
console.log('Mobile opt-in, preview isolation, search safety and translation checks passed.');
